package com.brown.asrs_user_authentication_api.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.time.LocalDateTime;

@Data
@Entity
@RequiredArgsConstructor
@Table(name = "Users_Authentication")
public class User {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;

        // Identity
        @Column(nullable = false, unique = true)
        private String email;        // username

        @Column(nullable = false)
        private String fullName;

        // Authentication
        @Column(nullable = false)
        private String password;

        // Authorization
        @Column(nullable = false)
        private String role;         // APPLICANT, REVIEWER, ADMIN
    @JsonProperty("phoneNumber")
    private String phoneNumber;
    @Column(nullable = true)
    private String address;

        // Status
        @Column(nullable = false)
        private Boolean active = true;

        // Audit
        @Column(nullable = false, updatable = false)
        private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // Constructors, getters, setters can be generated by Lombok
}
